safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "张植"
description: "现西安交通大学小硕一名"
baseurl: ""
url: "https://github.com/zhangzhi11" # replace by your site's url
twitter_username: your-name
github_username:  zhangzhi11 # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Zhang Zhi"
address: "碑林区咸宁西路28号，陕西西安"
email: "zhangzhi086@gmail.com"

# google analytics tracking code, please change the value
#g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
